// Code generated by scripts/regen-embedded.sh and scripts/build-singbox.sh; DO NOT EDIT.
package installer

const RequiredVersion = "1.14.0-alpha.34"

var EmbeddedBinaries = map[string]BinarySpec{
	"mipsel-3.4":   {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.34/sing-box-1.14.0-alpha.34-mipsel-3.4", SHA256: "a60b9a23e43d706ab04a9506a136f1a09b485ea5854965e34ecadd4744112ced", Size: 90709316},
	"mips-3.4":     {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.34/sing-box-1.14.0-alpha.34-mips-3.4", SHA256: "11a2aba2120c767b6aea03a65ad064e85822efb0b4f61c255dd19993b5fea98c", Size: 73466013},
	"aarch64-3.10": {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.34/sing-box-1.14.0-alpha.34-aarch64-3.10", SHA256: "d83f80b4b89bd2c8f6ff4d1a272e6d600eb56ecede5476d01848abf781b57ce1", Size: 76122136},
}
