// Code generated by scripts/regen-embedded.sh and scripts/build-singbox.sh; DO NOT EDIT.
package installer

const RequiredVersion = "1.14.0-alpha.42"

var EmbeddedBinaries = map[string]BinarySpec{
	"mipsel-3.4":   {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.42/sing-box-1.14.0-alpha.42-mipsel-3.4", SHA256: "a6591fc2200747532198119d892643f129247f1b322d2d50eae8d5ce46e2b8ca", Size: 91181136},
	"mips-3.4":     {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.42/sing-box-1.14.0-alpha.42-mips-3.4", SHA256: "6886cbacc7bc6b085ad6c35031548ca35ad833a6bcad078844fdbf2298263348", Size: 73924765},
	"aarch64-3.10": {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.42/sing-box-1.14.0-alpha.42-aarch64-3.10", SHA256: "ef6d4274ac3b5f69dd2d545df88f53c4437c8c71712dc379ca1675018890c53c", Size: 76528824},
}
